### ISSUE TITLE
Please clarify what version of Node.js is needed

### ISSUE THREAD

**Issue by SvenDowideit** [grafana/k6-template-typescript#41]
I happened to have v18.16.0 installed due to other things i'm working on, and on a fresh clone, I get:

```
dowideit.sven@ABC-KC00PW16GC k6 % npm install
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)

added 340 packages, and audited 341 packages in 6s

25 packages are looking for funding
  run `npm fund` for details

7 vulnerabilities (2 moderate, 4 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues, run:
  npm audit fix --force

Run `npm audit` for details.
dowideit.sven@ABC-KC00PW16GC k6 % npm start

> typescript@1.0.0 start
> webpack

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/Users/dowideit.sven/src/rockset/k6/node_modules/webpack/lib/util/createHash.js:144:18)
    at BulkUpdateDecorator.update (/Users/dowideit.sven/src/rockset/k6/node_modules/webpack/lib/util/createHash.js:46:50)
    at SourceMapSource.updateHash (/Users/dowideit.sven/src/rockset/k6/node_modules/webpack-sources/lib/SourceMapSource.js:233:8)
    at NormalModule._initBuildHash (/Users/dowideit.sven/src/rockset/k6/node_modules/webpack/lib/NormalModule.js:839:17)
    at handleParseResult (/Users/dowideit.sven/src/rockset/k6/node_modules/webpack/lib/NormalModule.js:904:10)
    at /Users/dowideit.sven/src/rockset/k6/node_modules/webpack/lib/NormalModule.js:995:4
    at processResult (/Users/dowideit.sven/src/rockset/k6/node_modules/webpack/lib/NormalModule.js:718:11)
    at /Users/dowideit.sven/src/rockset/k6/node_modules/webpack/lib/NormalModule.js:778:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.0
```

**Comment by mstoykov** [comment]
Hi , the error is already explored in #33. 

@ppcano has promised he will update the repo somewhat and maybe we will even move to rollup #34. 

As such I will close this as #33 already tracks the problem described here, which has more to do with the older version of webpack we are using.

**Comment by SvenDowideit** [comment]
@mstoykov nice!

Tho I suspect it is still worthwhile calling out the specific versions of node.js that you guys consider "resaonable" - 

do you expect node.js 14.x to work? or just from 18.0 up, etc

**Comment by mstoykov** [comment]
Given https://github.com/grafana/k6-template-typescript/blob/34f4a6afde336e3af9aba5302f628e54ae90c4d6/.github/workflows/push.yml#L17-L18  16 seems to be the expected version. 

But again this repo needs more then just this updated and if we move to rollup this will likely change
